config/routes.rb
Rails.application.routes.draw do

 root 'static_pages#home'
 get :about,        to: 'static_pages#about'
 get :use_of_terms, to: 'static_pages#terms'
 get :signup,       to: 'users#new'
 get    :login,     to: 'sessions#new'
 post   :login,     to: 'sessions#create'
 delete :logout,    to: 'sessions#destroy'
 resources :users do
    member do
      get :following, :followers
    end
  end
  resources :items

  resources :relationships, only: [:create, :destroy]
  get :favorites, to: 'favorites#index'
  post   "favorites/:item_id/create"  => "favorites#create"
  delete "favorites/:item_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  get :lists, to: 'lists#index'
  post   "lists/:item_id/create"  => "lists#create"
  delete "lists/:list_id/destroy" => "lists#destroy"
  resources :logs, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
     @feed_details = current_user.feed.paginate(page: params[:page], per_page: 5)
     @log = Log.new
    end
  end

  def about
  end

  def terms
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "バイログとは？") %>
<div id="fh5co-about">
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <h1 class="title-about">バイログとは？</h1>
        <h4>　自分が買ったり利用したりしたアイテムを、写真・メモ・ジャンルなどと共に記録できるサービスです。</h4>
      </div>
      <div class="col-md-10">
        <h2 class="title-use">主な使い方</h2>
        <div>
          <ol class="main-use">
            <li class="A">利用したモノや購入したアイテムの記録をする</li>
            <li class="B">友達や家族内でのアイテム共有サービスとして使う</li>
          </ol>
        </div>
        <p class="about-line"></p>
        <ol class="main-use">
          <li class="A">購入したアイテムの記録（ログ）として使う</li>
        </ol>
        <div class="use-content">
          <p>　　自分のアイテムや利用してよかったモノをどんどん記録しましょう。</p>
          <p>　「あのアイテムよかった（よい）かな？」と迷ったら、次に買うアイテムを</p>
          <p>　「お気に入り」や「リスト」から選んだり、検索して探したりすることができます。</p>
        </div>
        <ol class="how-to-use">
          <li>新しいアイテムを写真やメモと共に追加</li>
          <div class="use-explanation">
            <div class="row">
               <div class="col-md-4">
                <p>（1）「新しいアイテムを記録する」を<br>&emsp;&emsp;&emsp;&nbsp;クリックします。</p>
                <%= image_tag("/images/useA-1-1.png", :alt => "useA-1-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）アイテム情報を入力します。</p>
                <%= image_tag("/images/useA-1-2.png", :alt => "useA-1-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）アイテムの登録が完了しました！</p>
                <%= image_tag("/images/useA-1-3.png", :alt => "useA-1-3", class: "use-picture") %>
              </div>
            </div>
          </div>
          <li>買ったアイテムを「お気に入りに登録」</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）「お気に入りに登録する」を<br>&emsp;&emsp;&emsp;&nbsp;クリックします。</p>
                <%= image_tag("/images/useA-3-1.png", :alt => "useA-3-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）メニューから「お気に入り」を<br>&emsp;&emsp;&nbsp;クリックします。</p>
                <%= image_tag("/images/useA-3-2.png", :alt => "useA-3-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）お気に入り登録済みのアイテムを見る<br>&emsp;&emsp;&nbsp;ことができます。</p>
                <%= image_tag("/images/useA-3-3.png", :alt => "useA-3-3", class: "use-picture") %>
              </div>
            </div>
          </div>
          <li>登録済みのアイテムを「リスト」に追加</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）「買う予定リストに追加する」を<br>&emsp;&emsp;&emsp;&nbsp;クリックします。</p>
                <%= image_tag("/images/useA-4-1.png", :alt => "useA-4-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）メニューから「リスト」をクリック<br>&emsp;&emsp;&nbsp;します。</p>
                <%= image_tag("/images/useA-4-2.png", :alt => "useA-4-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）買う予定リストに追加済みのアイテム<br>&emsp;&emsp;&nbsp;を見ることができます。</p>
                 <%= image_tag("/images/useA-4-3.png", :alt => "useA-4-3", class: "use-picture") %>
              </div>
            </div>
          </div>
        </ol>
        <ol class="main-use">
          <li class="B">家族や友達内での買ったアイテムの共有サービスとして使う</li>
        </ol>
        <div class="use-content">
          <p>　　例えば家族や友達をフォローすれば、フォローした人の買ったモノを一覧で見ることができます。</p>
          <p>　　よかったアイテムをお気に入りに登録したり、コメントしたりできます。</p>
          <p>　「欲しい！」リクエストを送れば、アイテムを買った人の「リスト」に追加されます。</p>
        </div>
        <ol class="how-to-use">
          <li>アイテムにコメント（またはお気に入り登録）</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）アイテムのページへ飛び、コメントを<br>&emsp;&emsp;&nbsp;入力します。</p>
                <%= image_tag("/images/useB-1-1.png", :alt => "useB-1-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）コメント追加やお気に入りすると、<br>&emsp;&emsp;&nbsp;アイテムを買った人の通知メニューが<br>&emsp;&emsp;&nbsp;赤くなり通知されます。</p>
                <%= image_tag("/images/useB-1-2.png", :alt => "useB-1-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）アイテムを買った人にお気に入り登録<br>&emsp;&emsp;&nbsp;やコメントがあった旨の通知が届いて<br>&emsp;&emsp;&nbsp;います。</p>
                 <%= image_tag("/images/useB-1-3.png", :alt => "useB-1-3", class: "use-picture") %>
              </div>
            </div>
          </div>
          <li>アイテムに「欲しい！」リクエストを送る</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）欲しいアイテムの「欲しいリクエスト<br>&emsp;&emsp;&nbsp;を送る」をクリックします。</p>
                <%= image_tag("/images/useB-2-1.png", :alt => "useB-2-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）アイテムを買った人がメニューから<br>&emsp;&nbsp;&nbsp;「リスト」をクリックします。</p>
                <%= image_tag("/images/useB-2-2.png", :alt => "useB-2-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）「欲しいリクエスト」があったことが<br>&emsp;&emsp;&emsp;わかります。</p>
                <%= image_tag("/images/useB-2-3.png", :alt => "useB-2-3", class: "use-picture") %>
              </div>
            </div>
          </div>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div id="fh5co-portfolio">
    <div class="container">
      <div class="col-md-9">
        <h3>みんなのアイテム (<%= @feed_details.count %>)</h3>
        <%= render 'shared/feed' %>
      </div>
      <div class="col-md-3">
        <p><%= link_to "新しいアイテムを記録する", new_item_path, class: "btn btn-primary btn-lg btn-demo btn-record" %></p>
        <br>
      <p><%= link_to "みんなのアイテムをCSV出力", items_path(format: :csv), class: "btn btn-primary btn-lg btn-demo btn-csv" %></p>
      </div>
    </div>
  </div>
<% else %>
<%= render 'shared/recruit_login' %>
  <header id="fh5co-header" class="fh5co-cover js-fullheight" role="banner">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
          <div class="display-t js-fullheight">
            <div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
              <h1>買ったアイテムに、<br>写真やメモをつけて保存。</h1>
              <h2>レビューやクチコミ、もう迷わない！</h2>
              <p>
                <%= link_to 'バイログを始める', signup_path, class: "btn btn-primary btn-lg btn-demo" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
<% end %>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<div id="fh5co-about">
  <div class="container">
    <h1>利用規約</h1>
  </div>
</div>